spring:
  webflux:
    base-path: /iotenv/api/v1

logging:
  level:
    dev:
      sergevas:
        iot:
          env: DEBUG
    org:
      springframework:
        web: INFO
    reactor:
      netty:
        http:
          client: DEBUG

bh1750:
  #Default address for the GY-302 BH1750 module
  moduleAddress: 0x23
bme280:
  moduleAddress: 0x76
  forcedModeTimeout: 2000